#!/usr/bin/env bash

# Printed
print_info() {
    printf "$(tput setaf 4)Welcome back, $(tput setaf 5)$(if [[ $(getent passwd $(whoami) | cut -d ':' -f 5 | cut -d ',' -f 1 2>/dev/null) ]]; then echo $(getent passwd $(whoami) | cut -d ':' -f 5 | cut -d ',' -f 1); else echo $(whoami); fi)$(tput sgr0)\n\n"

    info "OS" distro
    info "KN" kernel
    info "SH" shell
    info "WM" wm
    info "UT" uptime
}


# Distro
distro_shorthand="off"
os_arch="off"


# Kernel
kernel_shorthand="on"


# Shell
shell_path="off"
shell_version="off"


# Uptime
uptime_shorthand="tiny"


# Text
colors=(0 0 0 4 4 5) 
bold="off"


# Image
image_backend="off"


# Config version. Do not change.
config_version="3.1.0"
